### ISSUE TITLE
patternlab init does not let me arrow through options

### ISSUE THREAD

**Issue by bmuenzenmeyer** [pattern-lab/patternlab-node-cli#29] opened 2017-02-02 05:58 UTC
### General information

When running `patternlab init` and interactively setting up a new project, I cannot arrow through edition options.

- NodeJS version: 4.6.2
- NPM version: 2.15.11
- Operating System: Windows

### Problem description
I wonder if this has to do with the node version, or the OS?

### Reproduction steps
![image](https://cloud.githubusercontent.com/assets/298435/22538737/45f447aa-e8da-11e6-8ee2-14b2fb33b6a5.png)

**Comment by benhalverson** [comment] 2017-02-02 06:48
@bmuenzenmeyer I think it's a OS issue. I am able to arrow up and down 
I switched my node to 4.6.2 using nvm
same version for npm 2.15.11
The only difference is I'm on osx 10.10.5

**Comment by raphaelokon** [comment] 2017-02-02 08:43
Possibly related https://github.com/SBoudrias/Inquirer.js/issues/303

Thanks @benhalverson for the check. I am closing this as I cannot reproduce it on 10.10.5 and Node v7.5.0

**Closed as completed by raphaelokon** 2017-02-02 08:43 UTC

**Comment by bmuenzenmeyer** [comment] 2017-02-02 13:25
Thanks for pointing that out! Will try an upgrade soon.
